title: Zheng Gao's Homepage
page-top-title: Zheng Gao
top-section-bg-text: Unity of knowledge and action
home-subtitle: Zheng Gao&ensp;|&ensp;高正
copyright-text: '&copy; Zheng Gao 2023-2024. All Rights Reserved.'
