# ===============================
#   Basic Site Info
# ===============================

title: "Zheng Gao's Homepage"
page-top-title: "Zheng Gao"
#top-section-bg-text: "Unity of knowledge and action"
home-subtitle: "Zheng Gao | 高正"
copyright-text: "© Zheng Gao 2023–2024. All Rights Reserved."

url: "https://gz107.github.io"
baseurl: ""

description: "Academic homepage of Zheng Gao."

# ===============================
#   Copyright
# ===============================
copyright-text: "© Zheng Gao 2023–2024. All Rights Reserved."